Fetch the Guzzle instance from the DI container, if it exists
bugsnag/bugsnag-laravel pull request #420
Opened 2020-11-18 16:08 UTC by imjoehaines

## Goal

This PR adds support for fetching the Guzzle instance from the DI container using the `bugsnag.guzzle` alias. If `bugsnag.guzzle` does not exist, one will be created as before

## Changeset

- Fetch `bugsnag.guzzle` from the DI container
- Set notify endpoint if config is set; this is because we previously set this on the guzzle instance we create, but it's needed for custom guzzle instances too
- Don't set guzzle base URI via `makeGuzzle`; this isn't needed with the above change

The remaining changes are to tests

## Testing

- Unit test proves the right guzzle instance is used
- MR tests prove a custom guzzle instance is used by adding a header in a guzzle middleware
- Also [forced the unstable tests to run](https://github.com/bugsnag/bugsnag-laravel/runs/1419129784) to check they still pass

2020-11-18 16:44 UTC, kattrali approved these changes

2020-11-18 23:22 UTC, GrahamCampbell requested changes

2020-11-18 23:22 UTC, GrahamCampbell commented on .ci/patches/register-custom-guzzle.patch
> ++        if (!getenv('BUGSNAG_USE_CUSTOM_GUZZLE')) {
`getenv` should be avoided (it is not threadsafe, which matters for php-fpm). Use the `Env` class in the php notifier.

2020-11-18 23:22 UTC, GrahamCampbell commented on .ci/patches/register-custom-guzzle.patch
> ++        if (!getenv('BUGSNAG_USE_CUSTOM_GUZZLE')) {
Actually, this probably isn't wanted anyway. Laravel doesn't load environment variables in production from dotenv files. This line can just be entirely deleted. People can still customize the guzzle instance by binding afterwards or using resolving callbacks.

2020-11-19 09:12 UTC, imjoehaines commented on .ci/patches/register-custom-guzzle.patch
> ++        if (!getenv('BUGSNAG_USE_CUSTOM_GUZZLE')) {
This is for a test fixture, not part of the library; specifically [this test](https://github.com/bugsnag/bugsnag-laravel/pull/420/files#diff-b0a0111e9fa7059461e9dbbce0198fa2a5412706873b9e8f6e2d71387bb6bdca)

2020-11-25 09:19 UTC, merged